### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by hackathi** [radiotap/python-radiotap#4]
Hey,

is it possible to make a pypi package for this library?

I could do a PR if needed.

**Comment by jmberg** [comment]
Is it even still relevant? I think we never updated this to e.g. parse TLV format...

But sure. I'm not against it. Not home though, so might be a while until I can do anything about it. 

On 9 July 2020 14:27:45 CEST, Katharina Bogad <notifications@github.com> wrote:
>Hey,
>
>is it possible to make a pypi package for this library?
>
>I could do a PR if needed.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/radiotap/python-radiotap/issues/4

-- 
Sent from my phone.

**Comment by techge** [comment]
> Is it even still relevant?

Is there a more complete python parser for radiotap etc.?

**Comment by jmberg** [comment]
Not that I know of. 

On 9 July 2020 15:23:08 CEST, Alexander Paetzelt <notifications@github.com> wrote:
>> Is it even still relevant?
>
>Is there a more complete python parser for radiotap etc.?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/radiotap/python-radiotap/issues/4#issuecomment-656124472

-- 
Sent from my phone.

**Comment by gpotter2** [comment]
You could use Scapy ([radiotap in scapy](https://github.com/secdev/scapy/blob/8153736544b8cedeabfdac81db1f92de6d12181d/scapy/layers/dot11.py#L262)) since that's already on PyPi but it's very different (probably slower if your intent is production, but fancy if you just want to play around, and with support for full 802.11 and building). It does have TLV support
